// File generated by FlutterFire CLI.
// Run: flutterfire configure --project=YOUR_FIREBASE_PROJECT_ID
// Then replace this file with the auto-generated one.
//
// IMPORTANT: Replace this file with your actual firebase_options.dart
// generated by running: flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ⚠️ TODO: Replace ALL values below with your Firebase project config
  // Get these from: Firebase Console > Project Settings > Your Apps

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGXtcecg7jK5bSb_2J8HeaOIQM7fv8CqM',
    appId: '1:366629806731:web:e3b627e34021052e89ea8e',
    messagingSenderId: '366629806731',
    projectId: 'safepay-28ea2',
    authDomain: 'safepay-28ea2.firebaseapp.com',
    storageBucket: 'safepay-28ea2.firebasestorage.app',
    measurementId: 'G-3V5PB0HJD7',
  );

  

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEU2uG77AbIRQQ-hMLmKcqwX35B1nF8iw',
    appId: '1:366629806731:android:0dad4b76fc7be56089ea8e',
    messagingSenderId: '366629806731',
    projectId: 'safepay-28ea2',
    storageBucket: 'safepay-28ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9MWD86ivlqxibP4cA5ayBZJD7tp2lX1o',
    appId: '1:366629806731:ios:74dd367f3499e97789ea8e',
    messagingSenderId: '366629806731',
    projectId: 'safepay-28ea2',
    storageBucket: 'safepay-28ea2.firebasestorage.app',
    iosBundleId: 'com.safepay.safepay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9MWD86ivlqxibP4cA5ayBZJD7tp2lX1o',
    appId: '1:366629806731:ios:74dd367f3499e97789ea8e',
    messagingSenderId: '366629806731',
    projectId: 'safepay-28ea2',
    storageBucket: 'safepay-28ea2.firebasestorage.app',
    iosBundleId: 'com.safepay.safepay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGXtcecg7jK5bSb_2J8HeaOIQM7fv8CqM',
    appId: '1:366629806731:web:8fb782609528ca5189ea8e',
    messagingSenderId: '366629806731',
    projectId: 'safepay-28ea2',
    authDomain: 'safepay-28ea2.firebaseapp.com',
    storageBucket: 'safepay-28ea2.firebasestorage.app',
    measurementId: 'G-X5W238HQ0F',
  );

}